# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('intro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('download_file', models.FileField(blank=True, null=True, upload_to='')),
                ('ext_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='regform',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Section'),
        ),
    ]
