# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20170921_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='section',
            name='title2',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
