# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20170921_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegHeaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='regform',
            name='image',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='intro',
        ),
        migrations.AlterField(
            model_name='regform',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_parts', to='registry.Section'),
        ),
        migrations.AddField(
            model_name='regform',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_header', to='registry.RegHeaderImage'),
            preserve_default=False,
        ),
    ]
