# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170919_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageheader',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
            preserve_default=False,
        ),
    ]
