# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_imageheader_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageheader',
            name='service',
        ),
        migrations.AddField(
            model_name='imageheader',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
