# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170922_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageheader',
            name='title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
