# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20170926_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='external_link2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='external_link3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='external_link4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
