# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170926_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_parts', to='services.Section'),
        ),
    ]
