# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certheader',
            old_name='description',
            new_name='intro',
        ),
    ]
