# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20170923_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
