# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='reason',
        ),
        migrations.AddField(
            model_name='marketing',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
