# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170919_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
