# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170919_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('intro', models.TextField()),
            ],
        ),
    ]
