# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170920_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='read_more',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
