# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_marketing_read_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('button', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
