# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='button',
            new_name='button_remind',
        ),
        migrations.AddField(
            model_name='reminder',
            name='button_renew',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
