# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170925_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='car_prove',
            new_name='car_proof',
        ),
    ]
