# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about'},
        ),
    ]
